//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingWilliam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=KingWilliamHotelDB;Integrated Security=True" +
            "")]
        public string KingWilliamHotelDBConnectionString {
            get {
                return ((string)(this["KingWilliamHotelDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\KingWilliamHo" +
            "telDB.mdf;Integrated Security=True;Connect Timeout=30")]
        public string KingWilliamHotelDBConnectionString1 {
            get {
                return ((string)(this["KingWilliamHotelDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-078D6KH;Initial Catalog=\"D:\\GOOGLE DRIVE\\MY COMPUT" +
            "ER\\DURHAM\\SEM 5\\DBAS\\DEL 4\\APPLICATION\\KINGWILLIAMHOTELDB.MDF\";Integrated Securi" +
            "ty=True")]
        public string D__GOOGLE_DRIVE_MY_COMPUTER_DURHAM_SEM_5_DBAS_DEL_4_APPLICATION_KINGWILLIAMHOTELDB_MDFConnectionString {
            get {
                return ((string)(this["D__GOOGLE_DRIVE_MY_COMPUTER_DURHAM_SEM_5_DBAS_DEL_4_APPLICATION_KINGWILLIAMHOTELD" +
                    "B_MDFConnectionString"]));
            }
        }
    }
}
